### ISSUE TITLE
Error - Unable to locate install app button by its description

### ISSUE THREAD

**Issue by walkermescc** [BadStreff/Enterprise-iOS-Apple-ID-Creator#1]
Hi,

Is there any chance you can have a look at this for us , we have tried looking at it and can't find the name of the Get button Description within iTunes.

![screen shot 2015-04-09 at 09 42 40](https://cloud.githubusercontent.com/assets/11868073/7063372/00d0d8ca-de9e-11e4-9472-e1b14eedc595.png)
![screen shot 2015-04-09 at 09 42 56](https://cloud.githubusercontent.com/assets/11868073/7063373/00d1efa8-de9e-11e4-9922-b019c2f9a5a7.png)

Regards,
Vincent Walker

**Comment by badstreff** [comment]
Can you verify the version of iTunes and OS X that you are using? Can you also verify that you are using 
the US version of the iTunes store?

I just ran a batch and everything is running currently.

Also verify that you have downloaded the script from my Github and not a version I posted on the enterprise iOS forums.
