### ISSUE TITLE
CSV Example

### ISSUE THREAD

**Issue by naildownx** [BadStreff/Enterprise-iOS-Apple-ID-Creator#2]
Do you have a link for an example CSV that your newest script requires?

I have no probs running the script in Terminal but I don't have anything to reference for the csv format.

Thanks man and great job!

Nails

**Comment by badstreff** [comment]
Sure thing, I just added an example csv. Further information for it can be found at the original scripts page.
http://www.enterpriseios.com/wiki/Batch_Apple_ID_Creator

Also, my apple id verification script will work with the same csv file.

Let me know if everything works out okay so I can close this ticket.

**Comment by naildownx** [comment]
Thanks! We will try this format and see if we can get it to work for us.

**Comment by naildownx** [comment]
I am currently running the script on my MacBook Pro now and creating the apple id's. Thank you for creating this version of this script. Awesome work! ~ Closing ticket.

**Comment by badstreff** [comment]
Awesome, glad to see it's working for someone besides me!
